/*
 * Generated by gdbus-codegen 2.56.4. DO NOT EDIT.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from.
 */

#ifndef __TILDA_DBUS_H__
#define __TILDA_DBUS_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for com.github.lanoxx.tilda.Actions */

#define TILDA_DBUS_TYPE_ACTIONS (tilda_dbus_actions_get_type ())
#define TILDA_DBUS_ACTIONS(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TILDA_DBUS_TYPE_ACTIONS, TildaDbusActions))
#define TILDA_DBUS_IS_ACTIONS(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TILDA_DBUS_TYPE_ACTIONS))
#define TILDA_DBUS_ACTIONS_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TILDA_DBUS_TYPE_ACTIONS, TildaDbusActionsIface))

struct _TildaDbusActions;
typedef struct _TildaDbusActions TildaDbusActions;
typedef struct _TildaDbusActionsIface TildaDbusActionsIface;

struct _TildaDbusActionsIface
{
  GTypeInterface parent_iface;

  gboolean (*handle_add_tab) (
    TildaDbusActions *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_command);

  gboolean (*handle_toggle) (
    TildaDbusActions *object,
    GDBusMethodInvocation *invocation);

};

GType tilda_dbus_actions_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *tilda_dbus_actions_interface_info (void);
guint tilda_dbus_actions_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void tilda_dbus_actions_complete_toggle (
    TildaDbusActions *object,
    GDBusMethodInvocation *invocation);

void tilda_dbus_actions_complete_add_tab (
    TildaDbusActions *object,
    GDBusMethodInvocation *invocation);






/* ---- */

#define TILDA_DBUS_TYPE_ACTIONS_SKELETON (tilda_dbus_actions_skeleton_get_type ())
#define TILDA_DBUS_ACTIONS_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TILDA_DBUS_TYPE_ACTIONS_SKELETON, TildaDbusActionsSkeleton))
#define TILDA_DBUS_ACTIONS_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TILDA_DBUS_TYPE_ACTIONS_SKELETON, TildaDbusActionsSkeletonClass))
#define TILDA_DBUS_ACTIONS_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TILDA_DBUS_TYPE_ACTIONS_SKELETON, TildaDbusActionsSkeletonClass))
#define TILDA_DBUS_IS_ACTIONS_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TILDA_DBUS_TYPE_ACTIONS_SKELETON))
#define TILDA_DBUS_IS_ACTIONS_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TILDA_DBUS_TYPE_ACTIONS_SKELETON))

typedef struct _TildaDbusActionsSkeleton TildaDbusActionsSkeleton;
typedef struct _TildaDbusActionsSkeletonClass TildaDbusActionsSkeletonClass;
typedef struct _TildaDbusActionsSkeletonPrivate TildaDbusActionsSkeletonPrivate;

struct _TildaDbusActionsSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  TildaDbusActionsSkeletonPrivate *priv;
};

struct _TildaDbusActionsSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType tilda_dbus_actions_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (TildaDbusActionsSkeleton, g_object_unref)
#endif

TildaDbusActions *tilda_dbus_actions_skeleton_new (const gchar *interface_name);


G_END_DECLS

#endif /* __TILDA_DBUS_H__ */
