/*
 * This file was generated by tilda dbus but subsequently modified to fit
 * out needs.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "tilda-dbus.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

/* ------------------------------------------------------------------------
 * Code for interface com.github.lanoxx.tilda.Actions
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:TildaDbusActions
 * @title: TildaDbusActions
 * @short_description: Generated C code for the com.github.lanoxx.tilda.Actions D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-com-github-lanoxx-tilda-Actions.top_of_page">com.github.lanoxx.tilda.Actions</link> D-Bus interface in C.
 */

/* ---- Introspection data for com.github.lanoxx.tilda.Actions ---- */

static const _ExtendedGDBusMethodInfo _tilda_dbus_actions_method_info_toggle =
{
  {
    -1,
    (gchar *) "Toggle",
    NULL,
    NULL,
    NULL
  },
  "handle-toggle",
  FALSE
};

static const _ExtendedGDBusArgInfo _tilda_dbus_actions_method_info_add_tab_IN_ARG_command =
{
  {
    -1,
    (gchar *) "command",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _tilda_dbus_actions_method_info_add_tab_IN_ARG_pointers[] =
{
  &_tilda_dbus_actions_method_info_add_tab_IN_ARG_command,
  NULL
};

static const _ExtendedGDBusMethodInfo _tilda_dbus_actions_method_info_add_tab =
{
  {
    -1,
    (gchar *) "AddTab",
    (GDBusArgInfo **) &_tilda_dbus_actions_method_info_add_tab_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-add-tab",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _tilda_dbus_actions_method_info_pointers[] =
{
  &_tilda_dbus_actions_method_info_toggle,
  &_tilda_dbus_actions_method_info_add_tab,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _tilda_dbus_actions_interface_info =
{
  {
    -1,
    (gchar *) "com.github.lanoxx.tilda.Actions",
    (GDBusMethodInfo **) &_tilda_dbus_actions_method_info_pointers,
    NULL,
    NULL,
    NULL
  },
  "actions",
};


/**
 * tilda_dbus_actions_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-com-github-lanoxx-tilda-Actions.top_of_page">com.github.lanoxx.tilda.Actions</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
tilda_dbus_actions_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_tilda_dbus_actions_interface_info.parent_struct;
}

/**
 * tilda_dbus_actions_override_properties:
 * @klass: The class structure for a #GObject derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #TildaDbusActions interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
tilda_dbus_actions_override_properties (GObjectClass *klass, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * TildaDbusActions:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-com-github-lanoxx-tilda-Actions.top_of_page">com.github.lanoxx.tilda.Actions</link>.
 */

/**
 * TildaDbusActionsIface:
 * @parent_iface: The parent interface.
 * @handle_add_tab: Handler for the #TildaDbusActions::handle-add-tab signal.
 * @handle_toggle: Handler for the #TildaDbusActions::handle-toggle signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-com-github-lanoxx-tilda-Actions.top_of_page">com.github.lanoxx.tilda.Actions</link>.
 */

typedef TildaDbusActionsIface TildaDbusActionsInterface;
G_DEFINE_INTERFACE (TildaDbusActions, tilda_dbus_actions, G_TYPE_OBJECT)

static void
tilda_dbus_actions_default_init (TildaDbusActionsIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * TildaDbusActions::handle-toggle:
   * @object: A #TildaDbusActions.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-github-lanoxx-tilda-Actions.Toggle">Toggle()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call tilda_dbus_actions_complete_toggle() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-toggle",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (TildaDbusActionsIface, handle_toggle),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * TildaDbusActions::handle-add-tab:
   * @object: A #TildaDbusActions.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_command: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-github-lanoxx-tilda-Actions.AddTab">AddTab()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call tilda_dbus_actions_complete_add_tab() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-add-tab",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (TildaDbusActionsIface, handle_add_tab),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

}

/**
 * tilda_dbus_actions_complete_toggle:
 * @object: A #TildaDbusActions.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-github-lanoxx-tilda-Actions.Toggle">Toggle()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
tilda_dbus_actions_complete_toggle (
    TildaDbusActions *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * tilda_dbus_actions_complete_add_tab:
 * @object: A #TildaDbusActions.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-github-lanoxx-tilda-Actions.AddTab">AddTab()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
tilda_dbus_actions_complete_add_tab (
    TildaDbusActions *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/* ------------------------------------------------------------------------ */

/**
 * TildaDbusActionsSkeleton:
 *
 * The #TildaDbusActionsSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * TildaDbusActionsSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #TildaDbusActionsSkeleton.
 */

struct _TildaDbusActionsSkeletonPrivate
{
  gchar *interface_name;
  _ExtendedGDBusInterfaceInfo interface_info;
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_tilda_dbus_actions_skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  TildaDbusActionsSkeleton *skeleton = TILDA_DBUS_ACTIONS_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  gsize num_params;
  guint num_extra;
  gsize n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], TILDA_DBUS_TYPE_ACTIONS);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TILDA_DBUS_TYPE_ACTIONS);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_tilda_dbus_actions_skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  TildaDbusActionsSkeleton *skeleton = TILDA_DBUS_ACTIONS_SKELETON (user_data);
  GDBusInterfaceInfo *interface_info = &skeleton->priv->interface_info.parent_struct;
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property (interface_info, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_tilda_dbus_actions_skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  TildaDbusActionsSkeleton *skeleton = TILDA_DBUS_ACTIONS_SKELETON (user_data);
  GDBusInterfaceInfo *interface_info = &skeleton->priv->interface_info.parent_struct;
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property (interface_info, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _tilda_dbus_actions_skeleton_vtable =
{
  _tilda_dbus_actions_skeleton_handle_method_call,
  _tilda_dbus_actions_skeleton_handle_get_property,
  _tilda_dbus_actions_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
tilda_dbus_actions_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *_skeleton)
{
  TildaDbusActionsSkeleton *skeleton = TILDA_DBUS_ACTIONS_SKELETON (_skeleton);

  return &skeleton->priv->interface_info.parent_struct;
}

static GDBusInterfaceVTable *
tilda_dbus_actions_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_tilda_dbus_actions_skeleton_vtable;
}

static GVariant *
tilda_dbus_actions_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  TildaDbusActionsSkeleton *skeleton = TILDA_DBUS_ACTIONS_SKELETON (_skeleton);
  gchar* interface_name = skeleton->priv->interface_name;
  GDBusInterfaceInfo *interface_info = &skeleton->priv->interface_info.parent_struct;

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (interface_info->properties == NULL)
    goto out;
  for (n = 0; interface_info->properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = interface_info->properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _tilda_dbus_actions_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), interface_name, info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
tilda_dbus_actions_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
}

static void tilda_dbus_actions_skeleton_iface_init (TildaDbusActionsIface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (TildaDbusActionsSkeleton, tilda_dbus_actions_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (TildaDbusActionsSkeleton)
                         G_IMPLEMENT_INTERFACE (TILDA_DBUS_TYPE_ACTIONS, tilda_dbus_actions_skeleton_iface_init))

#else
G_DEFINE_TYPE_WITH_CODE (TildaDbusActionsSkeleton, tilda_dbus_actions_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (TILDA_DBUS_TYPE_ACTIONS, tilda_dbus_actions_skeleton_iface_init))

#endif
static void
tilda_dbus_actions_skeleton_finalize (GObject *object)
{
  TildaDbusActionsSkeleton *skeleton = TILDA_DBUS_ACTIONS_SKELETON (object);

  g_free (skeleton->priv->interface_name);
  g_free (skeleton->priv->interface_info.parent_struct.name);

  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (tilda_dbus_actions_skeleton_parent_class)->finalize (object);
}

static void
tilda_dbus_actions_skeleton_init (TildaDbusActionsSkeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = tilda_dbus_actions_skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, TILDA_DBUS_TYPE_ACTIONS_SKELETON, TildaDbusActionsSkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
}

static void
tilda_dbus_actions_skeleton_class_init (TildaDbusActionsSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = tilda_dbus_actions_skeleton_finalize;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = tilda_dbus_actions_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = tilda_dbus_actions_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = tilda_dbus_actions_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = tilda_dbus_actions_skeleton_dbus_interface_get_vtable;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (TildaDbusActionsSkeletonPrivate));
#endif
}

static void
tilda_dbus_actions_skeleton_iface_init (TildaDbusActionsIface *iface)
{
}

/**
 * tilda_dbus_actions_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-com-github-lanoxx-tilda-Actions.top_of_page">com.github.lanoxx.tilda.Actions</link>.
 *
 * Returns: (transfer full) (type TildaDbusActionsSkeleton): The skeleton object.
 */
TildaDbusActions *
tilda_dbus_actions_skeleton_new (const gchar *interface_name)
{
  TildaDbusActionsSkeleton *skeleton;
  skeleton = TILDA_DBUS_ACTIONS_SKELETON (g_object_new (TILDA_DBUS_TYPE_ACTIONS_SKELETON, NULL));

  skeleton->priv->interface_name = g_strdup (interface_name);
  skeleton->priv->interface_info = _tilda_dbus_actions_interface_info;
  skeleton->priv->interface_info.parent_struct.name = g_strdup (interface_name);

  return TILDA_DBUS_ACTIONS (skeleton);
}
